# Generated by Django 5.2.8 on 2026-02-02 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_product_child_category_product_combo_size_config_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='selected_sizes',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
