# Generated by Django 5.2.8 on 2026-02-05 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_populate_parent_and_child_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentcategory',
            name='key',
            field=models.CharField(choices=[('upper', 'Upper'), ('lower', 'Lower'), ('shoes', 'Shoes'), ('combos', 'Combos')], max_length=50, unique=True),
        ),
    ]
