# Generated by Django 3.2.25 on 2025-11-07 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_orderproduct_variation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='secure_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
